
const Map<String,String> en = {

  "UpdateTime : " : "UpdateTime : ",
  "Show All Status" : "Current Details",
  "Status" : "Status",
  "Last Received Goods" : "Last Received Goods",
  "trackDet" : "Track The Goods By Shipping Number",
  "requestPin" : "Request Pin",
  "sendSms" : "Request Pin Over Sms",
  "noData" : "There is no data... If you need more information, Please contact to Atlas Port Customer Service",
  "newOrderNote":"Please add photos for one order only. You can add up to 5 photos.",
  "Good night!" : "Good night!",
  "Good morning!" : "Good morning!",
  "Good evening!" : "Good evening!",

  "updatePassword" : "Update Password",
  "newPassword" : "New Password",
  "confirmPassword" : "Confirm Password",
  "Profile" : "Profile",
  "No Last Collection": "No Last Collection",

  "Deleted!" : "Deleted!",
  "Are you sure?" : "Are you sure?",
  "You won't be able to revert this!" : "Delete the request permanently!",
  "Yes, delete it" : "Yes, delete it",
  "allTrips":"All Shipments",

  "Home" : "Home",
  "Shipments" : "Shipments",
  "Order" : "Order",
  "Orders" : "Orders",
  "R.Goods" : "R.Goods",
  "Cancel" : "Cancel",
  "Select Date Range" : "Select Date Range",


  "ats_tracking" : "ATS Tracking",
  "shipping_number" : "Track the goods by shipping number",
  "current_status" : "Current Status",
  "shipping_method" : "Shipping Method",
  "chart_shipping" : "Shipping Chart",
  "air_way" : "AirWay",
  "sea_way" : "SeaWay",
  "high_way" : "HighWay",
  "last_collection" : "Last Collection",
  "recod_date" : "Record Date",
  "popularـcompany" : "Most Popular Company",
  "brand" : "Company Brands",
  "total_goods" : "Received Goods Total",
  "received_goods" : "Last Received Goods",
  "lastـshipment" : "Last Shipment",


  "code" : "Code",
  "departure_date" : "S.Departure Date",
  "arrival_date" : "S.Arrival Date",
  "total_parcels" : "Total Parcels",
  "total_weight" : "Total Weight",
  "main" : "Main",
  "save" : "Save",
  "Please Select Image Source..." : "Please Select Image Source...",
  "Profile Image" : "Profile Image",
  "Address" : "Address",
  "selectUser" : "Select User",

  "phoneWA" : "Mobil (Whatsapp)",
  "market" : "Market Name",
  "country" : "Country",
  "city" : "City",
  "address" : "Address",
  "type" : "Which group products do you buy?",
  "passport" : "Passport",
  "searchCity" : "Search By City Name",
  "passportImage" : "Please upload a passport photo",
  "profileImage" : "Please upload your profile picture",
  "citySelect" : "Please select a city",
  "loading" : "Please Wait..",


  "name_hint" : "Phone",
  "sur_name" : "Surname",
  "error" : "Error",
  "login": "Login",
  "email": "Email",
  "pasaport_image": "Pasaport Image",
  "enter_email": "Enter your Email",
  "password": "Password",
  "password_matching": "Passwrod is not matching",
  "confirm_password": "Confirm Password",
  "update_password": "Update Password",
  "enter_password": "Enter your Password",
  "enter_phone": "Enter Phone Number",
  "again_later": "Please try again later",
  "select user": "Select User",
  "Forgot": "Forgot Password ?",
  "resend": "Re Send Pin Code",
  "check": "Check",
  "Account": "Don't have an Account ? ",
  "signup": "Sign Up",
  "error_password": "Error Password",
  "error_email": "Error Email",
  "error_name": "Error Name",
  "enter_name": "Name",
  "reg": "Become one of Atlas Port's customers",
  "regT": "Get all services for free\nafter joining the Atlas International\nCargo family",
  "close": "Close",
  "next": "Next",
  "ChooseLanguage": "Choose Your Preferred Language",
  "pleaseSelect": "please select your language",
  "SetLanguage": "Set Language",
  "state": "state",
  "errorMsg": "Please try again",
  "doneMsg": "Thank you for your interest, we will contact you as soon as possible, Atlas Port",
  "fill": "Please fill in all of the following information...",
  "pNumber": "Phone Number",
  "name": "Name",
  "sName": "SurName",
  "snedInfo":"Send Information",
  "          Open          ": "Open",
  "select_country": "Select Country",
  "select_city": "Enter Your City !",
  "phone": "Phone Number",
  "reg_suptitle": "successfully",
  "error_phone": "Phone Number Error",

  "approved" : "Approved",
  "waiting" : "Waiting",
  "deleted" : "Canceled",



  "Co.Phone\nNumber": "Co.Phone\nNumber",
  "Amount Paid": "Amount Paid",
  "Remaining": "Remaining",
  "Company Business Card": "Company Business Card",
  "No Image": "No Image",
  "Invoice Image": "Invoice Image",
  "back": "Back",

  "search": "Search",
  "Payment": "Payment",
  "pdf": "PDF",
  "date": "Date",
  "total": "Total",
  "company": "Company Name",
  "debt": "Debt",
  "amount": "Amount",
  "received_goods1": "Received Goods",
  "pieces": "Pieces",
  "box_pieces": "Box Pieces",
  "received_data": "Received Data",
  "branch": "Branch",
  "bag": "Bag",
  "box": "Box",
  "shipments": "Shipments",
  "send_date": "Send Date",
  "customer_total": "Customer Total",
  "parcels": "Parcels",
  "parcels_num": "Parcels Num",
  "unit_price": "Unit Price",
  "receivable": "Receivable",
  "paid": "Paid",
  "From:": "From",
  "To:": "To",

  "open": "open",
  "logout_title": "Logout",
  "logout_msg": "Are you sure you want to log out ?",
  "Complete Your Order": "Complete Your Order",



  "request":"Request",
  "tracking":"Track",

  "locationPermission" : "Location Permission",
  "locationNote" : "It is used during the delivery of goods upon arrival.",

  "xx": "xx",
  "cameraNote" : "It is used while adding a new request and changing the profile picture.",
  "storageNote" : "It is used while adding a new request and changing the profile picture.",
  "agree" : "Agree",
  "storagePermission" : "Storage Permission",
  "cameraPermission" : "Camera Permission",
  "permissionNote" : "By clicking on the OK button, you will activate the required permissions, allowing you to add new orders, change your profile picture, and track shipments by geographical location.",
  "amountPaid"  : "Paid",
  "remainingAmount"  : "Remain",
  "note"  : "Note",
  "New Order"  : "New Order",
  "addImage" : "Add An Image",
  "Camera" : "Camera",
  "Gallery" : "Gallery",
  "NoImage" : "No image added yet!",
  "ShippingMethod" : "Shipping Method",
  "Provision" : "Provision for Goods",
  "Cash" : "Cash by Hand",
  "shippingTypeError" : "choose the Shipping Method!",
  "remainingTypeError" : "choose the Order Type!",
  "done" : "Done",





  "Notifications" : "Notifications",
  "NotificationsSent" : "Notifications sent to you",
  "Rate" : "Rate App",
  "RateStore" : "Rate this app on the Store",
  "Share" : "Share",
  "ShareApp" : "Share the app",
  "TechnicalSupport" : "Technical Support",
  "ContactWhatsApp" : "Contact via WhatsApp",




};



