const Map<String,String> tr = {

  "cameraPermission" : "Kamera İzni",
  "UpdateTime : " : "Güncelleme Zamanı : ",
  "Show All Status" : "Cari Detay",
  "Last Received Goods" : "Son Mal Kabul",
  "trackDet" : "Gönderi Numarası ile Takip Et",
  "requestPin" : "Pin İste",
  "sendSms" : "Sms Üzerinden Pin İste",
  "noData" : "Hiç kayıt bulunamamıştır... Daha detaylı bilgi almak isterseniz, Atlas Port İletişim hatları üzerinden iletişime geçebilirsiniz.",
  "agree" : "Kabul etmek",
  "newOrderNote":"Lütfen sadece bir sipariş için fotoğraf ekleyiniz. En fazla 5 fotoğraf ekleyebilirsiniz.",
  "cameraNote" : "Profil resmini değiştirmek için ve yeni istek eklerken kullanılır.",
  "storageNote" : "Profil resmini değiştirmek için ve yeni istek eklerken kullanılır.",
  "Good night!" : "iyi geceler",
  "Good morning!" : "Günaydın!",
  "Good evening!" : "Ey Akşamlar",
  "loading" : "Lütfen bekleyin..",
  "resend": "Yeniden Gönder",
  "check": "Kontrol",
  "ChooseLanguage": "Tercih ettiğiniz Dili Seçin",
  "pleaseSelect": "lütfen dilinizi seçin",
  "SetLanguage": "Dili ayarla",

  "updatePassword" : "Şifreyi değiştir",
  "newPassword" : "Gizli Hayır",
  "confirmPassword" : "Şifreyi tekrar girin",
  "Cancel" : "İptal",
  "Select Date Range" : "Tarih Aralığı Seçin",
  "Profile" : "Profil",
  "No Last Collection": "Son Koleksiyon Yok",

  "Deleted!" : "silindi",
  "Are you sure?" : "Emin misin?",
  "You won't be able to revert this!" : "Delete the request permanently!",
  "Yes, delete it" : "Evet, sil",

  "allTrips":"Tüm gönderiler",

  "Home" : "Anasayfa",
  "Shipments" : "Gönderiler",
  "Order" : "Sipariş Ver",
  "Orders" : "Siparişler",
  "R.Goods" : "G.Mallar",
  "locationNote" : "Mal teslimi yapabilmek için konum bilgisi gereklidir.",
  "storagePermission" : "Depolama İzni",
  "request":"İstek",
  "tracking":"Takip",
  "locationPermission" : "Konum İzni",
  "permissionNote" : "Tamam düğmesine tıklayarak, yeni siparişler eklemenize, profil resminizi değiştirmenize ve gönderileri coğrafi konuma göre takip etmenize olanak tanıyan gerekli izinleri etkinleştireceksiniz.",
  "ats_tracking" : "ATS Takip",
  "shipping_number" : "Malları nakliye numarasına göre takip edin",
  "current_status" : "Cari Durum",
  "shipping_method" : "Nakliye Yöntemi",
  "air_way" : "HavaYolu",
  "sea_way" : "DenizYolu",
  "high_way" : "KaraYolu",
  "chart_shipping": "Grafik Nakliye",
  "last_collection": "Son Koleksiyon",
  "recod_date" : "Kayıt Tarihi",
  "popularـcompany" : "En Popüler Şirket",
  "brand" : "Şirket Markaları",
  "total_goods" : "Alınan Mal Toplamı",
  "received_goods" : "Son Alınan Ürünler",
  "lastـshipment" : "Son yükleme",


  "code" : "kod",
  "departure_date" : "Gönderi Çıkış Tarihi",
  "arrival_date" : "Gönderi Varış Tarihi",
  "total_parcels" : "Toplam Koli",
  "total_weight" : "Toplam ağırlık",
  "main" : "Ana",



  "approved" : "Onaylandı",
  "waiting" : "Beklemede",
  "deleted" : "İptal Edildi",





  "name_hint" : "Telefon",
  "sur_name" : "Soyadı",
  "error" : "Hata",
  "login": "Giriş",
  "Status" : "Durum",
  "email": "E-posta",
  "pasaport_image": "Pasaport Görüntüsü",
  "enter_email": "E-postanızı girin",
  "password": "Şifre",
  "password_matching": "Parola eşleşmiyor",
  "confirm_password": "Parolayı Onayla",
  "update_password": "Parolayı Güncelle",
  "enter_password": "Şifrenizi girin",
  "enter_phone": "Telefon Numarasını Girin",
  "again_later": "Lütfen daha sonra tekrar deneyiniz",
  "select user": "Kullanıcı seç",
  "Forgot": "Şifrenizi mi unuttunuz ?",
  "Account": "Hesabınız yok mu ? ",
  "signup": "Kaydol",
  "state": "Durum",
  "Please Select Image Source..." : "Lütfen bir görsel seçiniz...",
  "Profile Image" : "Profil Resmi",
  "save" : "Kaydet",
  "reg": "Atlas Port'un müşterilerinden biri olun",
  "regT": "Atlas Uluslararası\nKargo ailesine katıldıktan sonra\ntüm hizmetleri ücretsiz alın",
  "error_password": "Hata Parolası",
  "error_email": "Hata E-postası",
  "error_name": "Hata Adı",
  "enter_name": "Ad",
  "close": "Kapat",
  "next": "Sonraki",
  "errorMsg": "Lütfen tekrar deneyin",
  "doneMsg": "İlginiz için teşekkür ederiz, en kısa sürede sizinle iletişime geçeceğiz, Atlas Port",
  "fill": "Lütfen aşağıdaki bilgilerin tamamını doldurunuz...",
  "pNumber": "Telefon numarası",
  "name": "İsim",
  "sName": "Soyadı",
  "snedInfo":"Bilgi gönder",
  "          Open          ": "Aç",
  "open": "Aç",

  "select_country": "Ülke Seç",
  "select_city": "Şehrinizi Girin!",
  "phone": "Telefon Numarası",
  "reg_suptitle": "başarıyla",
  "error_phone": "Telefon Numarası Hatası",
  "Address" : "Adres",
  "selectUser" : "Kullanıcı seç",
  "back": "Geri",

  "phoneWA" : "Mobil Telefon (Whatsapp)",
  "market" : "Mağaza / Firma Adı",
  "country": "Ülke",
  "city" : "Şehir",
  "address" : "Adres",
  "type" : "Hangi grup ürünleri satın alıyorsunuz?",
  "passport" : "Pasaport",
  "searchCity" : "Şehir Adına Göre Ara",
  "passportImage" : "Lütfen pasaport fotoğrafını yükleyiniz",
  "profileImage" : "Lütfen profil fotoğrafınızı yükleyiniz",
  "citySelect" : "Lütfen bir şehir seçiniz",



  "Co.Phone\nNumber": "Şirket Telefon\nNumarası",
  "Amount Paid": "Ödenen Tutar",
  "Remaining": "Kalan",
  "Company Business Card": "Şirket Kartviziti",
  "No Image": "Görüntü Yok",
  "Invoice Image": "Fatura Resmi",
  "Complete Your Order": "Siparişinizi Tamamlayın",


  "search": "Arama",
  "pdf": "PDF",
  "date": "Tarih",
  "total": "Toplam",
  "company": "Şirket Adı",
  "debt": "Avans",
  "amount": "Tutar",
  "received_goods1": "Alınan Mallar",
  "pieces": "Parçalar",
  "box_pieces": "Kutu Parçaları",
  "received_data": "Alınan Veriler",
  "branch": "Branch",
  "bag": "Çanta",
  "box": "Box",
  "shipments": "Gönderiler",
  "send_date": "Gönderme Tarihi",
  "customer_total": "Müşteri Toplamı",
  "parcels": "Parseller",
  "parcels_num": "Parseller Num",
  "unit_price": "Birim Fiyat",
  "receivable": "Alacak",
  "paid": "Ücretli",
  "From:": "From",
  "To:": "To",
  "logout_title": "Çıkış",
  "logout_msg": "Çıkış yapmak istediğinizden emin misiniz ?",





  "xx": "Çıkış",


  "amountPaid"  : "Ödenen Tutar",
  "remainingAmount"  : "Kalan Tutar",
  "note"  : "Not",
  "New Order"  : "Yeni sipariş",
  "addImage" : "Resim Ekle",
  "Camera" : "Kamera",
  "Gallery" : "Galeri",
  "NoImage" : "Henüz hiç resim seçilmedi!",
  "ShippingMethod" : "Gönderi Yöntemi",
  "Provision" : "Mal Karşılığı",
  "Cash" : "Elden Nakit",
  "shippingTypeError" : "Gönderi Yöntemini seçmediniz!",
  "remainingTypeError" : "Sipariş Türünü seçmediniz!",
  "done" : "Tamam",



  "Notifications" : "Bilgilendirmeler",
  "NotificationsSent" : "Size gönderilen bilgilendirmeler",
  "Rate" : "Uygulamayı Puanla",
  "RateStore" : "Bu uygulamayı Mağazada puanla",
  "Share" : "Paylaş",
  "ShareApp" : "Uygulamayı paylaş",
  "TechnicalSupport" : "Teknik Destek",
  "ContactWhatsApp" : "Whatsapp üzerinden iletişime geç",

};



