name: zebraserviceprovider
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio:
  hive:
  get: ^4.6.6
  flutter_dropdown_alert:
  path_provider: ^2.0.15
  provider:
  device_info:
  flutter_spinkit:
  location:
  lottie:
  uuid:
  flutter_callkit_incoming: 1.0.3+3
  custom_pop_up_menu:
  statusbarmanager:
  advanced_icon:
  url_launcher: ^6.2.6
  flutter_launch:
  custom_timer: ^0.2.3
  whatsapp_unilink:
  google_maps_flutter: 2.2.3
  google_places_flutter:
  google_places_for_flutter:
  flutter_datetime_picker_plus:
  rating_dialog:
  intl: ^0.19.0
  #bs_flutter_buttons: ^1.2.8
  avatar_glow:
  assets_audio_player:
  flutter_animarker:
  #advanced_audio_manager:
  geolocator: 9.0.1
  webview_flutter: 3.0.4
  quickalert:
  toggle_switch:
  flutter_expanded_tile:
  flutter_webrtc: ^0.11.1
  proximity_sensor:
  http_parser:
  image_picker:
  firebase_messaging: 14.1.2
  firebase_core:
  geocoding:
  flutter_time_picker_spinner:
  flutter_incall_manager:
    git: https://github.com/manozzreddy/flutter-incall-manager.git
  socket_io_client:  2.0.1
  get_storage: ^2.1.1
  flutter_ringtone_player:
  widget_circular_animator:
  u_credit_card:
  flutter_chat_ui:
  hexcolor: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app/appLogo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/flags/
    - assets/app/
    - assets/icons/
    - assets/font/
    - assets/categoryIcons/

  fonts:
    - family: Century
      fonts:
        - asset: assets/font/Century Gothic.ttf

dependency_overrides:
  win32: ^5.5.4